### PR TITLE
Added package outline to F.Fab layer

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds package outline drawings to the F.Fab layer for each footprint in the Housings_QFP.pretty library.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@pointhi @diggit this one is pretty straight forward but adds some key improvements to existing footprints.

**Comment by SchrodingersGat** [comment]
e.g. 

fp

**Comment by pointhi** [comment]
I would suggest to also add a pin 1 marker on the F.Fab layer, because this is one of the usescases of the F.Fab layer. I know there should be a standard for it, but I don't know where I can find it. A circle like on the chip itself would be a good idea in my eyes.

**Comment by SchrodingersGat** [comment]
Good idea, done :)

**Comment by SchrodingersGat** [comment]
As per the discussion in https://github.com/KiCad/Housings_SSOP.pretty/pull/12 the circular pin-1 indicator has been added to F.Fab

**Comment by SchrodingersGat** [comment]
@CarlPoirier same changes have been made here also

**Comment by CarlPoirier** [comment]
Thank you Oliver, it's great!

**Pull request merged**
