### PR TITLE
add TQFP-100-1EP

### PR DESCRIPTION
**Pull request by lorem-ipsum**
just a copied TQFP-100 with the pad added to the center.
One chip which is using it is the Analog AD9910

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @lorem-ipsum  do you have a reference datasheet that shows the stencil requirements for the exposed pad?

**Comment by lorem-ipsum** [comment]
The only data sheet I have for that is the one for the AD9910, packaging is on page 62:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD9910.pdf

**Comment by SchrodingersGat** [comment]
@lorem-ipsum  fair enough, I couldn't find anything either.

Can you please add the package outline to the F.Fab layer with 0.05mm width line?

e.g.

tqfp

(I know that hasn't been done to the other TQFPs but as we're adding a new one we should do it as we go).

Thanks

**Comment by lorem-ipsum** [comment]
@SchrodingersGat done, I hope that's correct the way it is

**Comment by SchrodingersGat** [comment]
Thanks for your contribution :)

**Pull request merged**
