### PR TITLE
clearance settengs for TQFP 64 pin 10x10 footprint

### PR DESCRIPTION
**Pull request by poeschlr**
Fix for problem reported over at the info forum:
https://forum.kicad.info/t/footprints-soldermask-is-missing/7371

### CODE REVIEW

**Comment by evanshultz** [comment]
@poeschlr 
Normally I'd pull a simple fix like this right away, but one thing concerns me: the footprint name has an underscore before `1EP`. Shouldn't that be a hyphen, so the footprint name is `TQFP-64-1EP_10x10mm_Pitch0.5mm`? I also see `HTQFP-64_1EP_10x10mm_Pitch0.5mm_ThermalPad` is using an underscore but everywhere else in this library and other libraries I see or recall seeing hyphens.

**Comment by poeschlr** [comment]
@evanshultz i did not look at anything else than the problem i listed above.

@SchrodingersGat Thanks for the quick merge.

**Comment by evanshultz** [comment]
@poeschlr @SchrodingersGat 
That's great so the fix is implemented quick. But *should* it be a hyphen? I believe [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) clause 6.2 explicitly says this, and I'll whip up a PR to change underscores to hyphens unless I'm wrong.

**Comment by poeschlr** [comment]
I think you are correct. But should this footprint also include the information that the EP is partly covered by soldermask?

**Comment by evanshultz** [comment]
Yes, I would think so if the mask over copper were intentional. Here it seems to be a mistake. I've not seen that before. What is the requirement/case where the mask should cover the thermal pad of a QFP?

**Comment by poeschlr** [comment]
It might be on purpose.
Example for a component that needs such a footprint where the EP is partly covered with soldermask:
(TI-bq76pl536)
http://www.ti.com/lit/ds/slusa08a/slusa08a.pdf

**Comment by evanshultz** [comment]
Interesting. This datasheet does recommend having the stencil smaller than the copper pad. I've done this when the part was dropped into a big copper zone as part of the board design, but I hadn't seen this before. Thanks for the link!

PR submitted to change underscore to hyphen: https://github.com/KiCad/Housings_QFP.pretty/pull/22. And, as it turns out, this same problem exists in other footprints as well. I agree that if this is part of the footprint the name should reflect it. If the name doesn't call out a shrunk soldermask, the mask clearance should be 0.

**Pull request merged**
