### PR TITLE
Add PQFP footprints from SMD_Packages

### PR DESCRIPTION
**Pull request by evanshultz**
Part of my continuing efforts to fix up the libraries, continuing from discussion at https://github.com/KiCad/SMD_Packages.pretty/issues/20. Made all footprints KLC compliant.

Some of these packages seem to be rarely used now, and I included the 386 footprint more as a novelty. I can't imagine who would use it these days, but it used to be in the library...

Datasheets:
http://www.nxp.com/docs/en/application-note/AN4388.pdf (general pad design equations)
https://www.altera.com/content/dam/altera-www/global/en_US/pdfs/literature/ds/pkgds.pdf
https://www.intel.com/content/dam/www/public/us/en/documents/packaging-databooks/packaging-chapter-02-databook.pdf (removed "ears" for normal 132 pin)
http://cache.freescale.com/files/shared/doc/package_info/98ASS23330W.pdf (lqfp but looks OK)

Image:
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz the only thing I would suggest is that given the large amount of space inside each component, the value field (e.g. PQFP-etc-etc) could be moved inside the body outline, to reduce the overall size of the footprints.

Other than that I am happy to merge.

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks! Done.

**Comment by evanshultz** [comment]
@SchrodingersGat Oliver?

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
