### PR TITLE
Added LQFP-80_10x10mm_Pitch0.4mm

### PR DESCRIPTION
**Pull request by Matthias-C**
The package is using the 0.5mm pitch 3D model with 0.8 scaling

Signed-off-by: Matthias Clemen matthias-clemen@gmx.de

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @Matthias-C please have a look at the updated footprints in this repository. Of particular note:

* Add the component outline to the F.Fab layer, width=0.15mm, with a 1mm bevel at the top-left corner to indicate pin-1
* Please adjust the silkscreen to match the pattern of the other QFP chips

**Comment by Matthias-C** [comment]
Thank you @SchrodingersGat  for your Comment and Suggestions. 
I hope now everything is as it should be and the Pull Request can be approved.

**Comment by SchrodingersGat** [comment]
Almost :) Just change the width of the courtyard layer to 0.05mm (down from 0.15mm) Thanks

**Comment by Matthias-C** [comment]
Done. Sorry i missed that.
BTW. 
1) I really like your work for the Community @SchrodingersGat 
2) First pull request ever :)

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: LQFP-80_10x10mm_Pitch0.4mm
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

**Comment by evanshultz** [comment]
Closing and re-opening to trigger Travis.

**Comment by evanshultz** [comment]
@Matthias-C 
I've trigger the automatic rules checker (you can find the rules, called KLC, [here](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)). You can click on the Details link above to see the 3 issues it caught. Can you please fix this items?

Next, please attach a part datasheet that uses this footprint for verification.

Here is an image of the footprint:
image

I have the following requests after reviewing your contribution:
- Please add a link to the footprint in description
- The courtyard is 0.5mm from the part body/pads, but it should be 0.25mm away on a 0.1mm grid.
- Silkscreen should be just outside the part body (F.Fab lines) or half overlapping. Yours is too far away.
- Move the silkscreen ref des out from underneath the part body.
- You will need to add the following to create a second ref des on the F.Fab layer:
```
(fp_text user %R (at 0 0) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.1)))
  )
```

**Comment by Matthias-C** [comment]
frist the datasheet for refrence
http://www.wiznet.io/wp-content/uploads/wiznethome/Chip/W5100/Document/W5100_Datasheet_v1.2.7.pdf

**Comment by evanshultz** [comment]
@Matthias-C 
Thanks for updating the footprint and providing a datasheet!

Very close. Just a couple more changes:
- This datasheet doesn't show the recommended PCB footprint, only the package dimensions. [This link](http://old.wiznet.co.kr/sub_modules/en/technical/Q_A_View.asp?boardcd=101&SF_AO=&PK_NUM=25529&page=188&SF_Part=boardno,%20writer,%20subject,%20contents&SF_KeyWord=&SF_AO=) seems to say Wiznet doesn't supply one. Are you able to find it so I can verify the copper?
- The courtyard should be on a 0.1mm grid. For this footprint, you'll need to go away from the pads 0.05mm more which will end up being 0.3mm away from the pads (courtyard corners at 6.4,6.4).

By the way, if you haven't seen the rules for the KiCad library you will find them at https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

**Comment by Matthias-C** [comment]
Hi and thanks for your reply,
I will try to find a date sheet for verification, when i originally created this pull request i couldn't find one but i will look at it again.

For the country yard i looked up the klc and in 7.5.3 it says it should be on the 0.01 grid. This should not implz that im not willing to change my design.

**Comment by evanshultz** [comment]
You're right! Most 80-pin LQFPs seem to be bigger in size, or the 10x10mm ones are fewer pins.

I was able to find relevant information from [Renesas' LQFP package list page](https://www.renesas.com/en-us/search/package-list.html?category=IC&type=LFQFP):
- Package drawing: https://www.renesas.com/ko-kr/package-image/pdf/outdrawing/plqp0080la_a.pdf
- Pad dimensions: https://www.renesas.com/en-us/package-image/pdf/mountpad/fig0009e.pdf

After reviewing the Renesas data, here is what I see:
1. Your pads are 1.2mm long and Renesas says they should be 0.55-0.95mm.
1. Your pad spacing is smaller than the 0.2mm they recommend.

[Intersil also has a package drawing](http://www.intersil.com/content/dam/Intersil/documents/q80_/q80.10x10.pdf) for this LQFP. I see that your 0.23x1.2mm pads are exactly what Intersil recommends, but it shows the pad outer edges at 12.6mm while yours are 12.2mm.

Unfortunately I didn't see anything else after several minutes of searching. Can you find anything? I'd like to have more references to check against. It may be that this package will need to be manufacturer-specific, but I haven't seen enough to know if there is a common/standard footprint and only one of the above is unique.

I've read KLC a number of times and I had already read `0.1mm` for the courtyard grid. I apologize. You're right that it is `0.01mm`, and thank you for pointing out my error.

**Comment by Matthias-C** [comment]
Pretty much the same on my side i found the intersil doc you mentioned and some general document fron nxp an4388  it's more like a general guide line for all lqfp packages. I will investigate this issue in greater detail tomorrow. For that i will go through some other manufactures and look for their recommended 80-lqfp 0.4 layout.

**Comment by evanshultz** [comment]
In the interest of finding out the only answer Wiznet provided, I installed Eagle (oh the humanity!) and opened the board file they mentioned (in my comment above). While I couldn't find how to open the library footprint, I cranked the grid down to 0.01mm and made the following measurements:
- Pad size: 1.04x0.24mm
- Pad row inner-to-inner distance: 10.72mm
- Pad row outer-to-outer distance: 12.80mm

Here is an image:
image

Not sure what this tells us for sure, but it's something. Please add this to the info you can find online and then we'll better know if there's a standard package or we need to use a prefix to indicate this part is specific to just one vendor.

**Comment by Matthias-C** [comment]
Did some further searching so my findings so far
Other parts using the 80-LQFP 10x10 footprint 
-  [microchip KSZ8795CLX](http://ww1.microchip.com/downloads/en/DeviceDoc/00002112B.pdf)
found some other part from Diodes and intersil but the datasheet was not that helpful most of  the 80-LQFP are using the 0.5 pitch 

SRC | Pad H | Pad W | Dist In | Dist Out
-- | -- | -- | -- | --
Eagle Wiznet (yours) | 1,04 | 0,24 | 10,72 | 12,8
Mine | 1,2 | 0,23 | 9,8 | 12,2
intersil q80.10x10.pdf | 1,2 | 0,23 | 10,2 | 12,6
microchip KSZ8795CLX | 1 | 0,2 | 10,4 | 12,4

a bunch of links

http://home.jeita.or.jp/tsc/std-pdf/EDR-7311A.pdf |  Standart ??
https://www.sparkfun.com/datasheets/DevTools/Arduino/W5100_Datasheet_v1_1_6.pdf |  
https://www.renesas.com/ko-kr/package-image/pdf/outdrawing/plqp0080la_a.pdf | chip layout
http://www.intersil.com/content/dam/Intersil/documents/q80_/q80.10x10.pdf |  With layout
http://www.holtek.com.tw/documents/10179/116723/lqfp80-1010.pdf| chip layout
http://www.ipassion.com.tw/pdf/iP2986.pdf| chip layout
http://ww1.microchip.com/downloads/en/DeviceDoc/00002112B.pdf |  With layout

After reading  the recommendations from [NXP](http://www.nxp.com/docs/en/application-note/AN4388.pdf) and [renesas](https://www.renesas.com/en-us/package-image/pdf/mountpad/fig0009e.pdf ) and reviewing the Datasheets found. I  recommend the following

Pad H | Pad W | Dist In | Dist Out
-- | -- | -- | --
1,1 | 0,23 | 10,5 | 12,7

I moved the inside of the pads further out to respect the in the NXP pdf mentioned clearance for reflow soldering. I sicked with the in the intersil mentioned Width of the pads, (it matches the max width of the leads) and should be small enough to avoid bridging. (fingers crossed). The length of the pads is a little bigger than the size of the chip (12mm + 0,35mm per side) witch sounds reasonable and is inside the recommendations (NXP and intersil). 

If this is fine with you I will change the Footprint tomorrow (europe) and push it.

**Comment by Matthias-C** [comment]
image
Here the updates as mentioned above

**Comment by evanshultz** [comment]
@Matthias-C 
Thanks for this thorough research!

My fear with making the inner distance farther apart is that we won't get a nice fillet on the inside of the lead. The fillet on the outside will necessarily be small since the lead is quite thin (from the PCB surface). That means we won't need the pad outer distance won't need to be much more than 12mm (the distance across the tips of the pins) but having the inner pad distance closer to 10mm (but not more, or else solder can flow under the package body) will help. Since the pads are thinner, making them longer will help.

Consider this, I think the Intersil layout is the best way to go. It avoids pads less than 10mm apart, gives good marking past the pin tips, and has large pads to accommodate most parts. Do you agree? Sorry that this will require another change, but if you can adjust to the Intersil layout, or suggest something better, I'll merge.

Thanks again for your contribution!

**Comment by Matthias-C** [comment]
bildschirmfoto vom 2017-07-25 22-27-16
bildschirmfoto vom 2017-07-25 22-27-55

Changed the Footprint to the intersil settings.
also did a quick and diry wrl model in open scad.

**Comment by poeschlr** [comment]
For footprints similar to this there is a 3d model generator over at the repo by @easyw
(The QFN generator should be easily adaptable to generate this model.)
That generator creates the correctly scaled wrl model with nice colors and a step model for use in 3d mcad programs. If you are interested in playing around with the generator but need help just either ask here, over at the generator repo or over at the info forum.

https://github.com/poeschlr/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/QFN_packages

This does not mean we will not accept your 3d model. If yours is correctly scaled we can add it to the legacy lib ([kicad-library repo subfolder modules/packages3d](https://github.com/KiCad/kicad-library/tree/master/modules/packages3d)) if you can also supply a correctly scaled step model we can add it to the new lib ([packages3d](https://github.com/KiCad/packages3D)) as well.

**Comment by evanshultz** [comment]
Hi @Matthias-C This looks great! Thank you.

One small thing before I merge: I see the NXP app note is mentioned in the description. Can you please change that to the Intersil document?

**Comment by easyw** [comment]
If possible, for uniformity of the library, I would suggest to try to make the model with the scripts, just adding the right parameters...

**Comment by evanshultz** [comment]
@Matthias-C 
Thanks for your work to make this footprint and for your patience to update it!

**Pull request merged**
