### PR TITLE
Add LQFP-32-1EP_5x5mm_Pitch0.5mm.kicad_mod

### PR DESCRIPTION
**Pull request by rdeterre**
Thermal pad was designed based on [the MSP430 datasheet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCUQFjABahUKEwiu7u-moKrIAhUGdx4KHdJ3AE8&url=http%3A%2F%2Fwww.ti.com%2Flit%2Fds%2Fsymlink%2Fmsp430f2132.pdf&usg=AFQjCNH0t2fvkk2xlQcneZMh5eB_AC5vww&sig2=GCMUPBz1dcQUymS-mduqQQ). Is there a place where I should put the relevant section of that file in the repo?

Thanks

### CODE REVIEW

**Comment by pointhi** [comment]
I would propose you to change the Thermal pad of the footprint like it's already done for other 1EP Footprints (splitting them in multiple pads with special settings for the solder mask).

The Datasheet already propose an example stencile design

(@CarlPoirier, @ricardocrudo are there specific IPC rules which we are following for thermal pads, or are such example design sufficient?)

**Comment by rdeterre** [comment]
Thanks for the feedback. The thermal pad design is now modified according to the datasheet. Should the solder mask clearance be adjusted as well to follow the datasheet's recommendations, or is it better to leave it as is for consistency with the other footprints?

**Comment by pointhi** [comment]
Hy, the footprint looks good now. 

One KLC issue is left:
```
checking module: LQFP-32-1EP_5x5mm_Pitch0.5mm
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

**Comment by rdeterre** [comment]
I think the footprint passes KLC now. The 3D model points to a missing location now though. Please let me know if doing a PR on `kicad-library` that adds renamed versions of `LQFP-32-1EP_5x5mm_Pitch0.5mm.wings` and `LQFP-32-1EP_5x5mm_Pitch0.5mm.wrl` is the right way.

**Comment by pointhi** [comment]
Thanks for your contribution

**Pull request merged**
