### PR TITLE
Create SW-64-2.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
Analog devices SW-64-2 footprint.
10x10mm housing and 64 pins, pitch 0.5
the footprint from ultra librarian was useless and wrong.

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: SW-64-2
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
```

* Also mark pin 1 in a standardised way (look onto the other footprints and http://www.pcblibraries.com/forum/smt-library-silkscreen-outlines_topic26.html)

can you tell me what was wrong with the normal LQFP-64 footprint?
http://www.analog.com/media/en/technical-documentation/data-sheets/ADV7611.pdf

**Comment by savenlid** [comment]
"generic" footprint does not match analog devices suggested footprint.

professional designer do not use generic footprints.

its like your generic 0402 footprint.

it did not match the murata GRM15 series footprint for capacitorsm it does
not match KOA 0402 resitors and it does not match murata inductors 0402
footprint

all 3 of them are diffrent albeit all are "0402" with a component body or
0.5x1mmm and none matched kicad 0402

i could upload my footprints but all of them gets rejected,

you know KLC says keep courtyard 0.25mm , well many designs could not be
done with that courtyard.

for example 0201 components you want to place tight and this fully depends
on capabilities of the pick-and place equipment.
you dont want kicad courtyard rules to cut you short.

sorry.

Kicad urgently need to get their library functionallityy in to shape and i
dont talk about the github part beacuse i gave up on that.

drop the active library concept and everything will be easier,
add a part concept where you tie togheter symbol and footprint.
take a look at other tools out there, mentor dx designer and cadence.

just suggestions.

i am working 100% ahead so i dont have the time to do klc, either you add
the footprints to your library so you get something useful or you discard
them

i just tried to give something back,

many thanks
Nichoilas




2016-02-16 22:48 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
hy @savenlid,

I can understand your complaints, but you have to note some time ago the KLC was invented to work towards a homogeneous library which should fit basic requirements in quality and usablitiy. Therefore, for example the courtjard is normaly using the recommendations for a "Nominal Enviroment" which should fit for most people, but like you said not for all.

> for example 0201 components you want to place tight and this fully depends on capabilities of the pick-and place equipment.

This stuff is already concerned in the KLC ```6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm```

Creating component specific footprint shouldn't be a problem for the kicad-library as long as they are KLC complicant. Simply using a naming scheme like ```GenericFootprintName-PackageOption.kicad_mod``` so everyone can spot them easily.

> i am working 100% ahead so i dont have the time to do klc, either you add the footprints to your library so you get something useful or you discard them

You did good work, especially for the Fabrication Layer. I leave the PR open, so someone can fix the remaining problems sometime.

**Comment by savenlid** [comment]
if i get time i will fix

but i struggle with bugs in pcbnew

a component with a 0402 footprint that previosly loaded perfectly now wont
load.
reads the netlist no problem but show the 0402 cap as one "pin" on top
layer copper but in wrong color but if you untick the top it disappears so
he associates with top layer copper but in wrong color etc etc

aoowwww


i have footprints for 0402 to upload that have the name of the suggested
manufacturers foot print.

i upload them also, you can have a look at them

thanks
/Nicholas


2016-02-16 23:44 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by savenlid** [comment]
I undesrtood from docs you should have normal+insert for smd componentes
(altough i have ni idea what is is all about)

but how could i set the soldermask to zero and get a completely undefined
soldermask in my footprint ?

you must understand that that is out of the question, you must be able to
know that your footprint will be used and not some oter suspisous rule,

why on earth would anyone ever ever have a main design rule for soldermask
margin.

other tools dont have it and its for a very good reason, soldermask margins
only appear within footprints sp why should there be a design value for
that.
never heard of before.
not in mentor not in cadence.

sorry but it would be crazy to not let the footprint define itself and be
overruled by unknown varying factors.

typically you let the pad itself define all layers, but kicad dont have pad
library.

i will do the notmal+insert from now on in my library for smd parts.


thanks
/Nicholas


2016-02-16 22:48 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by michal777** [comment]
It's not true that a footprint defined by manufacturer of the component must be better. It's more important to design the footprint for specific pcb manufacturing and assembling technology. As long as manufacturer of your component in the quad flat package don't know your pick-and-place tolerances, pcb tolerances, heating profiles etc his suggested land pattern may be worse than some generic one (like a footprint calculated according to IPC7351).
Many packages are quite standard and similar so there is no need to care about small differences in their tolerances (I don't think that every professional designer cares about it).
Most of packages in this library are not generic (references in footprint descriptions). The footprints will be typically ok for many users and probably there is no need for many duplicates. If somebody wants really good footprint he still should design it (considering his specific pcb and assembly technology and dimensions and tolerances of the component).

**Comment by savenlid** [comment]
Semi true.

Mostly things mount ok if the footprint is not very wrong.

Pcb is pcb not much can differ between same surface treatment.
Pick and place all place in correct place,  never heard anything else.

Solder itself can hace some impact as the reflow curve.

But Datasheet suggestions are almost always the best to follow.

IPC,  yes I like IPC,  but then save them with IPC numbers so I know it is
IPC.

Many thanks.
/Nicholas
Den 18 feb 2016 12:17 AM skrev "michal777" <notifications@github.com>:

**Comment by savenlid** [comment]
For qfn they will mount unless something is very wrong.

But it's always good to have one foot print dedicated per chip maker.

Not seldom same footprint name can vary so much between manufacturers that
you can not mount.

For 0402 0201 components it's crucial to not follow generic footprints or
you run the risk of tombstones.

0402 is also modified a lot with clipped cities to be able to mount
underneath bga in between bga break out vias.

Thanks again.
/Nicholas
Den 18 feb 2016 12:17 AM skrev "michal777" <notifications@github.com>:

**Comment by savenlid** [comment]
HI

"your" footprint
MSOP-8_3x3mm_Pitch0.65mm

passes KLC probably but its just plain wrong.
no assembly drawing /fab)

but worse of all the pads are not on 0.65mm pitch

instead of being on 0.65/2= 0.3125 they are on a 0.325 offset.

ouch

I can supply soon the micrel footprint for the same, its called mm8 and
will be correct.
i do a pull

thanks
/Nicholas


2016-02-16 22:48 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by savenlid** [comment]
ignore this email it was wrong of me


2016-02-19 19:10 GMT+07:00 Nicholas Sävenlid <nicholas@savenlid.se>:

**Comment by savenlid** [comment]
Hi

Could you make repository "Maxim.IC"  ?

maxim has all their own footprint drawings and I would love to upload the
ones i have made for the benefit of all other kicad users.

Could you make an IPC folder as well ?
would love to make some IPC footprints.

thanks
/Nicholas

example:
http://pdfserv.maximintegrated.com/land_patterns/90-0059.PDF

2016-02-16 22:48 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
I think it's more purposeful to use the existing repositories and name the footprints something like ```TDFN-8-1EP_3x3mm_Pitch0.65mm_Maxim.kicad_mod``` in https://github.com/KiCad/Housings_DFN_QFN.pretty

The ```GenericName_VenderName.kicad_mod``` scheme as proposed earlier is easier to spot, and is also more KLC compliant:

```
7.4. If it's a manufacturer-specific package, name can be appended, separated by an underscore.
```

**Comment by savenlid** [comment]
its a dfn, if there is a dfn repo i put it there
prefxed maxim_

2016-02-22 17:15 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by pointhi** [comment]
There are various Housing_xxx.pretty for different footprints, including one for DFN available.
I think using a postfix as suggested is the better variation, because then you see the different varations next to each other

**Comment by savenlid** [comment]
thanks

you are free to rename it as you want but normally a designer knows what
components he has choosen for example maxim and if he looks in dfn the
maxims comes in order.

but you are free to rename as you see fit.

IPC repo should exist tough and I would prefer we call footprints by their
ipc-number and not a long story of someones life, just the number and be
done.

beacuse if you look for a ipc thnk you know its namber and its number you
want to find.
if you look for a maxim-ic footprint thats what you want to look for, no
the generic text browsing.

sorry, its just how it is

agree to disagree


2016-02-22 18:57 GMT+07:00 Thomas Pointhuber <notifications@github.com>:

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by evanshultz** [comment]
@hackscribble You self-assigned this PR, so are you planning to make changes? It's unclear to me if there are issues with the existing footprint, and otherwise this conversation is off topic. I vote to close this issue unless you're planning some work or there's more definition to the problem this PR will solve.

**Comment by hackscribble** [comment]
I self-assigned to track the old PRs I had looked at in my first pass.  So OK to close.

**Pull request closed without merging**
