### PR TITLE
Change underscore before "1EP" to hyphen

### PR DESCRIPTION
**Pull request by evanshultz**
Just as it says, from discussion at #20.

### CODE REVIEW

**Comment by evanshultz** [comment]
These two footprints also have a shrunk solder mask. Remove this here as well?

**Comment by evanshultz** [comment]
Can I get an answer to my question and a review, please?

**Comment by poeschlr** [comment]
I think the shrunk soldermask might be on purpose. Maybe rename it to indicate this fact?
(In addition you could add a copy without shrunk solder mask.)

The ThermalPad suffix for the HTQFP footprint seems a bit out of place. Would TheremalVias be a more fitting suffix?

Do we have a script to check if these footprints are referenced in a symbol of our lib? (Renaming footprints means we might need to update these scripts.)

**Comment by SchrodingersGat** [comment]
Rene, I am planning to add such functionality to the script here - https://github.com/KiCad/kicad-library-utils/pull/138

**Comment by poeschlr** [comment]
Naming see naming convention issue https://github.com/KiCad/kicad-library/issues/1447

Copper on back for footprints with thermal vias:
I think no. (This came up already somewhere else.)
It is much more flexible without an additional copper pad on the back. That way users can decide which layer they want to connect to a large copper plain. (If they even want to connect to a plain)

**Comment by SchrodingersGat** [comment]
@evanshultz 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
