### PR TITLE
Create TQFP-80-1EP_14x14mm_Pitch0.65mm.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Baesd off of the existing footprint without a thermal pad.

Datasheet: http://www.analog.com/media/en/technical-documentation/data-sheets/AD9852.pdf

And since ADI is so lame as to not post PDF footprint drawings, here is Ultra Librarian:
image

Image:
image

The KLC violations are for using one big copper pad with 4 smaller stencil openings in it.

### CODE REVIEW

**Comment by evanshultz** [comment]
Can this be merged?

**Comment by evanshultz** [comment]
Can I get a review, please?

**Comment by evanshultz** [comment]
@jkriege2 You're on a roll today! Are you available to look at this one?

**Comment by jkriege2** [comment]
looks good ... coudln't you simply number the pads that cause the errors also 81? The effect should be the same and the errors should go away ... or is there another reason to keep the the way they are now?

**Comment by evanshultz** [comment]
@jkriege2 Just tried that and, as I thought, it still gives the same number of KLC errors using the current script design.

It was my understanding to do the pins like this based on discussion at https://github.com/KiCad/LEDs.pretty/pull/39 and Oliver merging that PR with the same issues.

This method does create a lot of errors but it generates footprints that match the datasheet and known good design practices. I think the root problem is an error of the script methodology. It requires a paste layer to exist for each pad. Perhaps a better way would be to have the script check if a copper pad has mask and paste layers, or check that there are multiple pads with the same number that together have copper, mask and paste? I can still see errors with this method, but they should be less.

At any rate, I'll be happy to open an issue about this for the scripts to start discussion on best to handle this type of padstack, but in the interim I believe the KLC "violations" are of no concern. Agree?

**Comment by jkriege2** [comment]
OK then I'll merge ... if you come up with a script-fix for this problem, that would be great!

Best,
JAN

**Pull request merged**
