### PR TITLE
Add LQFP-144 with 4..9 mm exposed pads

### PR DESCRIPTION
**Pull request by krtkr**
Hi all!

I am working on adding Altera devices to Kicad. Altera FPGA's use QFP packages with exposed pads (EP) of different sizes.

It seems current naming convention does not include EP size. I suggest following convention: -1EP[size_mm]mm_.

I add 5 packages:
1. LQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm
1. LQFP-144-1EP_20x20mm_P0.5mm_EP5x5mm
1. LQFP-144-1EP_20x20mm_P0.5mm_EP6.61x6.61mm
1. LQFP-144-1EP_20x20mm_P0.5mm_EP7.2x7.2mm
1. LQFP-144-1EP_20x20mm_P0.5mm_EP8.93x8.93mm

All these packages are copy of LQFP-144_20x20mm_Pitch0.5mm with a single pad in center.

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you list datasheets that specify these footprints?
(These datsheets should also be linked in the description field of the footprints)

Have a look at the exposed pad. Normally the paste layer should be broken up into multiple smaller squares. This might be either specified in the datasheet directly or in an application note.
Example for such an application note (yes it is for a qfn package and by ti but something similar will apply here as well)
http://www.ti.com/lit/an/sloa122/sloa122.pdf

A better more detailed application note (the interesting part is on page 5 and page 6)
http://www.psemi.com/pdf/app_notes/an62.pdf
>It is a good practice to minimize voids within the exposed pad interconnection, so the design 
of the exposed pad stencil is crucial. The proposed stencil design enables out gassing of the 
solder paste during reflow and also regulates the finished solder thickness. Typically, the 
stencil apertures are reduced such that the solder paste coverage is 50% to 70% of the 
exposed pad area.

**Comment by krtkr** [comment]
Thank you for the comment! Quite interesting.

I have updated footprints to comply with stencil design requirements. Now all footprints should have around 60% paste coverage.

Also add links to footprint documentation provided by Altera company.

**Comment by poeschlr** [comment]
For naming convention i would suggest to have both the x and y size of the exposed pad in the name. (In future someone might commit a part with an exposed pad differing in these directions.)

I opened an issue for exactly this discussion:
https://github.com/KiCad/kicad-library/issues/1447

**Comment by poeschlr** [comment]
Sorry for my late response. The naming convention has been fixed. (A while ago but i forgot to notify you.)
{}: denotes optional field
[]: denotes a variable

`{[Manufacturer name]_}[package name]-[pin count]{-[EP qty]EP}_[Size x]x[Size y]{x[Height]}mm_P[pin pitch]mm{_EP[Size x]x[Size y]mm{_Mask[Size x]x[Size y]mm}}{_Pad[pad length]{x[pad width]}}{_footprint options}`

- If the footprint has an exposed pad it needs to include the following:
   - The EP qty field needs to exist
   -  The size of the exposed pad needs to be given
   -  If the soldermask cutout for the exposed pad is reduced, its resulting size needs to be given.

This would mean your first package (currently `LQFP-144-1EP4x4mm_20x20mm_Pitch0.5mm`) should be named:
`LQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm`

**Comment by krtkr** [comment]
Hey,
I am back again. Footprint names update according to new KLC.

**Comment by jkriege2** [comment]
@poeschlr A note on the naming scheme ... the abbreviations are a bit puzzlin here, as once the EP appears as postfix of the number of exposed pads and once as prefix for their size. Also the EP is very close to the P used for Pitch and a P appears three times in this name .... maybe there's a better solution?

JAN

**Comment by poeschlr** [comment]
Well the naming convention discussion was open for at least two month and nobody suggested something better. (Saying something is not quite right is really easy. Coming up with an alternative is way harder.)

**Comment by jkriege2** [comment]
I stick to my suggestion to not use abbreviations, especially not the P, which could stand for Package, Pitch, (exposed) Pad, (exposed) Pad Size, Pin, ...

A suggestion from me would be e.g. `LQFP-144-1EP_20x20mm_Pitch0.5mm_EPadSize4x4mm`

... but then my arguments for more verbose (and therefore better understandable, even without having a table of abbreviationsbesides) names was not heard so far.

**Comment by SchrodingersGat** [comment]
No matter where we draw the line we must define a convention somewhere. I think that in this case Jan has a valid point that EP is used twice. `EPSize` is a good compromise I think...

**Comment by poeschlr** [comment]
@krtkr sorry that your thread is used for this discussion. Your contribution is the one contribution that showed us this edge case. (And that inspired the inclusion of the mandatory EP Size field within the footprint names.)

**Comment by SchrodingersGat** [comment]
@krtkr 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
